// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90n696lq_8IxECe6otvylLyGoWtBWO-o',
    appId: '1:242511635900:web:2ecde2bf61ea7649b437b9',
    messagingSenderId: '242511635900',
    projectId: 'smartroute-ai-ae0d5',
    authDomain: 'smartroute-ai-ae0d5.firebaseapp.com',
    storageBucket: 'smartroute-ai-ae0d5.firebasestorage.app',
    measurementId: 'G-8KYJ3ZLRB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl_OjEgP1NduvLVn6rCjmTdS1NSs3cQhU',
    appId: '1:242511635900:android:f1eb171a8d609271b437b9',
    messagingSenderId: '242511635900',
    projectId: 'smartroute-ai-ae0d5',
    storageBucket: 'smartroute-ai-ae0d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgxKIBPqRfps9h1zNUiQiEZSReamXoJMc',
    appId: '1:242511635900:ios:f7846a6a7dc46bb3b437b9',
    messagingSenderId: '242511635900',
    projectId: 'smartroute-ai-ae0d5',
    storageBucket: 'smartroute-ai-ae0d5.firebasestorage.app',
    androidClientId: '242511635900-tu475uab0dmmp49lrqmtn8idcrgditdo.apps.googleusercontent.com',
    iosClientId: '242511635900-s7if5hbq8uoisf8egqmjd0trfo6d878o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartrouteAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgxKIBPqRfps9h1zNUiQiEZSReamXoJMc',
    appId: '1:242511635900:ios:f7846a6a7dc46bb3b437b9',
    messagingSenderId: '242511635900',
    projectId: 'smartroute-ai-ae0d5',
    storageBucket: 'smartroute-ai-ae0d5.firebasestorage.app',
    androidClientId: '242511635900-tu475uab0dmmp49lrqmtn8idcrgditdo.apps.googleusercontent.com',
    iosClientId: '242511635900-s7if5hbq8uoisf8egqmjd0trfo6d878o.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartrouteAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA90n696lq_8IxECe6otvylLyGoWtBWO-o',
    appId: '1:242511635900:web:b6087f02dc37e87eb437b9',
    messagingSenderId: '242511635900',
    projectId: 'smartroute-ai-ae0d5',
    authDomain: 'smartroute-ai-ae0d5.firebaseapp.com',
    storageBucket: 'smartroute-ai-ae0d5.firebasestorage.app',
    measurementId: 'G-2VV98K6FZY',
  );
}
